name: "Helm Publish"
description: "Package and push Helm chart"

inputs:
  token:
    description: "GitHub secret"
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug PWD
      run: |
        echo "Current directory:"
        pwd
        echo "Contents:"
        ls -la
      shell: bash

    - name: Helm lint
      run: helm lint .
      shell: bash

    - name: Helm package
      id: package
      run: |
        OUTPUT=$(helm package .)
        echo "$OUTPUT"
        FILE_NAME=$(echo "$OUTPUT" | grep -o '[^ ]\+\.tgz')
        echo "📦 Chart packaged as: $FILE_NAME"
        echo "TAR_CHART=$FILE_NAME" >> $GITHUB_ENV
        echo "PACKAGE_FILE=$FILE_NAME" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to GHCR
      run: echo "${{ inputs.token }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Push Helm chart
      run: |
        echo "Pushing ${{ env.TAR_CHART }}"
        helm push ${{ env.TAR_CHART }} oci://ghcr.io/francsco99
      shell: bash
