name: "Helm Publish"
description: "Package and push Helm chart"

inputs:
  token:
    description: "GitHub PAT"
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug workspace
      run: |
        echo "PWD: $(pwd)"
        echo "Repo contents:"
        ls -la
      shell: bash

    - name: Lint chart
      run: helm lint .
      shell: bash

    - name: Package chart
      id: package
      run: |
        OUTPUT=$(helm package .)
        echo "$OUTPUT"
        FILE_NAME=$(echo "$OUTPUT" | grep -o '[^ ]\+\.tgz')
        echo "PACKAGED_CHART=$FILE_NAME"
        echo "TAR_CHART=$FILE_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Log in to GHCR
      run: echo "${{ inputs.token }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Push chart
      run: |
        echo "Pushing ${{ env.TAR_CHART }}"
        helm push ${{ env.TAR_CHART }} oci://ghcr.io/francsco99
      shell: bash
