name: v1 Publish Helm Chart Dry

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      version:
        required: true
        type: string # 'major', 'minor', 'patch'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Run Helm Publish Composite Action
        uses: ./.github/actions/helm-publish
        with:
          token: ${{ secrets.GHCR_PAT }}
          version: ${{ inputs.version }}   
