name: v1 Publish Helm Chart

run-name: Publish Helm Chart on branch -> ${{ inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: main

jobs:
  publish-helm-chart:
    uses: ./.github/workflows/helm-publish-dry.yaml
    permissions:
      contents: write
      packages: write
    with:
      branch: ${{ inputs.branch }}
    secrets: inherit
